config/routes.rb
Rails.application.routes.draw do
root "lessons#index"
resources :lessons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/lessons', to: 'lessons#index', as: 'lessons'
  # get 'lessons/new', to :'lessons#new'
  # post '/lessons', to : 'lessons#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    validates :student_name, presence: true
    validates :instrument, presence: true
    validates :lesson_number, presence: true
    validates :lesson_topic, presence: true
    validates :lesson_description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :set_lesson, only: [:show, :edit, :update, :destroy]
   
#index all lessons
def index
    @lessons = Lesson.all
end

#rendering new lesson
def new
    @lesson = Lesson.new
end

#show lesson
def show
end

#create new lesson log
def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
        redirect_to @lesson, notice: 'Lesson successfully logged.'    
    else
        render :new
    end
end

def edit
    @patient = Lesson.find(params[:id])
end

#update lesson log
def update
    if @lesson.update(lesson_params)
        redirect_to @lesson, notice: 'Lesson log was successfully updated.'
    else
        render :edit
    end
end

#delete lesson log
def destroy
    @lesson.destroy
    redirect_to root_path, notice: 'Lesson log was successfully destroyed.'
end

private
    def set_lesson
        @lesson = Lesson.find(params[:id])
    end

    def lesson_params
        params.require(:lesson).permit(:student_name, :instrument, :lesson_number, :lesson_date, :lesson_topic, :lesson_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicLessons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
<div class="form-group">
    <%= form.label :student_name, style: 'padding: 1em' %>    
    <%= form.text_field :student_name, class: 'form-control', style: 'width:40%' %>
</div>

<div class="form-group">
    <%= form.label :instrument, style: 'padding: 1em' %>
    <%= form.text_field :instrument, class: 'form-control', style: 'width:40%' %>
</div>

<div class="form-group">
    <%= form.label :lesson_number, style: 'padding: 1em' %>
    <%= form.number_field :lesson_number, class: 'form-control', style: 'width: 40%' %>
</div>

<div class="form-group">
    <%= form.label :lesson_date, style: 'padding: 1em' %>
    <%= form.date_field :lesson_date, class: 'form-control', style: 'width: 40%' %>
</div>

<div class="form-group">
    <%= form.label :lesson_topic, style: 'padding: 1em' %>
    <%= form.text_field :lesson_topic, class: 'form-control', style: 'width: 40%' %>
</div>

<div class="form-group">
    <%= form.label :lesson_description, style: 'padding: 1em' %>
    <%= form.text_field :lesson_description, class: 'form-control', style: 'width: 40%' %>
</div>

<div class="actions">
    <%= form.submit %>
</div>

<%end%>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h2>

<%= render 'form', lesson: @lesson %>

app/views/lessons/index.html.erb
<div class="table-responsive">
<h1>Students List</h1>
<table class="table table-striped border-dark">
    <thead>
    <tr>
        <th scope="col">Student Name</th>
        <th scope="col">Instrument</th>
        <th scope="col">Session</th>
        <th scope="col" colspan="3" >Options</th>
    </tr>
    </thead>

    <tbody>
        <% @lessons.each do |lesson| %>
            <tr>
                <td><%= lesson.student_name %></td>
                <td><%= lesson.instrument %></td>
                <td><%= lesson.lesson_number %></td>
                <td><%= link_to 'Show', lesson%></td>
                <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
                <td><%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure you want to delete this log?' } %></td>
            </tr>
            <%end%>
        </tbody>
    </table>

    <br> 

<button type="button" class="btn btn-outline-primary" data-mdb-ripple-color="light">
    <p class="text"><%= link_to 'Create New Lesson Log', new_lesson_path %></P>
</button>       

</div>

app/views/lessons/new.html.erb
<h1>Add Lesson Log</h1>

<%= render 'form', lesson: @lesson %>
<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<div class="table-responsive">
<h3>Student Name: <%= @lesson.student_name %></h3>
<h4>Date of lesson: <%= @lesson.lesson_date%></h4>

<table class="table table-striped border-dark">
    <tr>
        <th scope="col">Lesson Number</th>
        <th scope="col">Lesson Topic</th>
        <th scope="col">Lesson Description</th>
    </tr>
    <tr>
        <td><%= @lesson.lesson_number%></td>
        <td><%= @lesson.lesson_topic%></td>
        <td><%= @lesson.lesson_description%></td>
    </tr>
</table>

<br>

<%= link_to "Edit", edit_lesson_path(@lesson)%>
<%= link_to 'Delete', @lesson, method: :delete, data: { confirm: 'Are you sure you want to delete this log?' } %>
<%= link_to 'Back', root_path(@lesson) %>
</div>